runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: app.main.app

- url: /api/.*
  script: app.main.app

- url: /fetch/
  script: app.main.app
  login: admin

skip_files:
- tests/
- env/
- .git/
